### ISSUE TITLE
Этап 1

### ISSUE THREAD

**Issue by Sinamore** [FomichevAK106/MSUTask6#1]
**На каждый из последующих пунктов нужно ответить отдельным комментарием: либо со ссылкой на коммит, исправляющий ошибку/недочет, либо с ответом на вопрос.**

_30.04_

1. <s>Нет Makefile</s>
2. <s>Компиляция с `-Wall -Wextra` выдает предупреждения</s>
3. <s>Комментарии кириллицей (предпочтителен английский)</s>
4. <s>Из вывода программы неясно, каким методом и на каких отрезках решается задача (но хорошо, что есть точность и true val)</s>
5. <s>Нет автоматической проверки корректности результата</s>
6. Как были выбраны `ROOTPRECISION` и `INTEGRALPRECISION`?
7. <s>Для вычисления модуля стоит использовать функцию `fabs`</s>

Поддержка знаковости интеграла -- хорошо.

**Comment by FomichevAK106** [comment]
1. Добавлен Makefile.
2. Исправлено
3. Исправлено
4. Добавлено описание.
5. Добавлено.
6. Пояснение в README.md.
7. Замена проведена.
