### ISSUE TITLE
Этап 2

### ISSUE THREAD

**Issue by Sinamore** [FomichevAK106/MSUTask6#2]
**На каждый из последующих пунктов нужно ответить отдельным комментарием: либо со ссылкой на коммит, исправляющий ошибку/недочет, либо с ответом на вопрос.**

_12.05_

1. <s>В репозитории де-факто два проекта, нужно оставить только вторую версию (и положить в корень)</s>
2. Висящие пробелы в Makefile, functions.asm, main.c => остались в functions.asm
3. <s>Makefile: clear => clean</s>
4. <s>Нужно инициализировать сопроцессор</s>
5. <s>В выводе не хватает информации о том, какую задачу решает программа, на каких данных, какими методами (можно убрать под флаг `-v` или `-verbose`) => `-verbose` должен добавлять информацию к выводу, не отменяя решения основной задачи </s>
6. <s>Флаг `pretest` должен запускать только тесты, но не основную программу (то же для `root_t` и `integral_t`)</s>
7. <s>Программа принимает некорректные значения аргументов (в `root_t` и `integral_t`), но не сигнализирует об этом => все еще верно для номера функции и `eps`</s>
8. <s>Программа не проверяет количество позиционных аргументов для `root_t` и `integral_t`</s>
9. <s>https://github.com/FomichevAK106/MSUTask6/issues/1#issue-873226800</s>
10. <s>Нужно разбить большой `main.c` на несколько файлов по смыслу (как минимум на основной код и тестирующий)</s>

_14.05_

11. <s>`root_t` и `integral_t` не принимают отрицательные числа в качестве аргументов для координат</s>

**Comment by FomichevAK106** [comment]
1. Теперь проект один.
2. Убраны.
3. Исправлено.
4. Исправлено.
5. Добавлен аргумент -verbose.
6. Теперь работает именно так для pretest, root_t, integral_t, verbose.
7. Добавлена обработка некорректных данных.
8. Добавлена обработка недостаточного количества аргументов. Избыточные аргументы игнорируются.
9. Добавлен комментарий к Issue #1. (Не уверен, что правильно понял этот пункт)
10. Программа разбита на файлы.

**Comment by Sinamore** [comment]
Исправить к финальной версии (сдаваемой с отчетом):

1. Чтобы не принимать аргументы вида 123ohnoitsastring: https://stackoverflow.com/questions/13701657/control-whole-string-with-sscanf
2. У `-root_t` не хватает проверки, что `from <= to` 
3. `make clean` не должен удалять `main`
